name: build-and-run-mambo
run-name: Running GitHub Action
on: [push]
jobs:
  build-and-run-mambo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: mambo
          submodules: true
      - run: sudo apt-get update
      # - run: sudo apt-get upgrade
      - run: sudo apt-get install -y debootstrap
      - run: sudo apt-get install -y qemu-user-static
      - run: mkdir -p /tmp/chroot/
      - run: sudo debootstrap --arch=riscv64 --foreign focal /tmp/chroot/riscv64 http://ports.ubuntu.com/ubuntu-ports
      - run: sudo cp /usr/bin/qemu-riscv64-static /tmp/chroot/riscv64/usr/bin/
      - run: sudo chroot /tmp/chroot/riscv64/ /usr/bin/qemu-riscv64-static /bin/bash -c '/debootstrap/debootstrap --second-stage'
      - run: sudo cp -r $GITHUB_WORKSPACE/mambo /tmp/chroot/riscv64/root
      - run: sudo chroot /tmp/chroot/riscv64/ /usr/bin/qemu-riscv64-static /bin/bash -c 'sudo apt-get update; sudo apt-get upgrade -y; sudo apt-get -y install build-essential libelf-dev ruby; cd /root/mambo/; make'
      - run: sudo chroot /tmp/chroot/riscv64/ /usr/bin/qemu-riscv64-static /bin/bash -c '/root/mambo/dbm /bin/ls'
